<?php

namespace ScufBundle\Repository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActionByTypeAndUser($type, $userID)
    {
        $queryBuilder = $this->_em->createQueryBuilder('a')
            ->select('a.id, a.created, a.updated, a.start, a.end, a.status, a.justification, (a.user) AS user')
            ->from('ScufBundle:Action', 'a')
            ->where('a.type = :type AND a.user = :id')
            ->setParameter('type', $type)
            ->setParameter('id', $userID);
        $query = $queryBuilder->getQuery();
        $actions = $query->getResult();
        return $actions;
    }
}
