<?php

namespace ScufBundle\Repository;

/**
 * EventParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventParentRepository extends \Doctrine\ORM\EntityRepository
{
}
