<?php

namespace ScufBundle\Repository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByGroupAndSlug($group, $slug)
    {
        $queryBuilder = $this->_em->createQueryBuilder('s')
            ->select('s.id, s.title, s.value')
            ->from('ScufBundle:Setting', 's')
            ->where('s.group = :group AND s.slug = :slug')
            ->setParameter('group', $group)
            ->setParameter('slug', $slug);
        $query = $queryBuilder->getQuery();
        $settings = $query->getResult();
        return $settings;
    }
}
