<?php

namespace ScufBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchUser($term)
    {
        $queryBuilder = $this->_em->createQueryBuilder('u')
            ->where('CONCAT(u.firstname, \' \', u.lastname) LIKE :firstname :lastname')
            ->setParameter('firstname', '%'.$term.'%')
            ->setParameter('lastname', '%'.$term.'%');
        $query = $queryBuilder->getQuery();
        $item = $query->getResult();
        return $item;
    }

    public function getSuperior($userID)
    {
        $queryBuilder = $this->_em->createQueryBuilder('u')
            ->select('(u.superior)')
            ->from('ScufBundle:User', 'u')
            ->where('u.id = :id')
            ->setParameter('id', $userID);
        $query = $queryBuilder->getQuery();
        $superior = $query->getResult();
        return $superior;
    }

    public function findTypeByUserAndWeek($userID, $number)
    {
        $queryBuilder = $this->_em->createQueryBuilder('w')
            ->select('w.setting')
            ->from('ScufBundle:Week', 'w')
            ->where('w.number = :number AND w.user = :user')
            ->setParameter('number', $number)
            ->setParameter('user', $userID);
        $query = $queryBuilder->getQuery();
        $settingID = $query->getResult();
        return $settingID;
    }
}
